name: 'Manage Issue Subscribers'
description: 'Automatically CC people based on labels.'
author: '@zpao'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'lib/main.js'
